apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: highload-project
  labels:
    app: nginx
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80