apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume
  namespace: highload-project
  labels:
    app: db
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem