apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: highload-project
  labels:
    app: db
    tier: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db