apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: highload-project
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "512m"
            memory: "128Mi"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: static-volume
          mountPath: /static
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc