apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: highload-project
spec:
  selector:
    app: rabbitmq
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 31672
    - name: amqp
      port: 5672
      targetPort: 5672
  type: NodePort